# CI acts as a automatic code reviewer + validator
# Meaning: “Whenever code changes, automatically check that it doesn’t break things.”

# Example workflow:

# You make code change
#       ↓
# push to feature branch/dev branch
#       ↓
# GitHub automatically runs checks
#       ↓
# PASS ✅ or FAIL ❌
#       ↓
# Then create PR(Pull Request) to main

# Example in your project

# Suppose tomorrow you accidentally break:

# consumer/kafka_to_s3.py

# by missing a bracket:

# print("hello"

# You push code.

# CI runs:

# python -m compileall .

# and fails.

# GitHub says:

# ❌ CI failed
# Syntax error

# before you merge to main.

# That is CI.



# Name of workflow shown in GitHub Actions UI
name: CI

# Defines WHEN this workflow should run
on:

  # Run workflow whenever code is pushed
  push:

    # Only run if push happens to these branches
    branches:
      - main
      - dev

  # Run workflow when a pull request is opened
  # into main branch
  pull_request:
    branches:
      - main


# Jobs = actual tasks GitHub Actions executes
jobs:

  # Name of our job
  validate-project:

    # GitHub creates a temporary Ubuntu VM
    # to run all commands below
    runs-on: ubuntu-latest

    # Steps = sequence of commands
    steps:

      # Step 1:
      # Clone/download your GitHub repository
      # into GitHub runner machine
      - name: Checkout repository
        uses: actions/checkout@v4


      # Step 2:
      # Install Python so GitHub runner can run
      # your python scripts
      - name: Setup Python
        uses: actions/setup-python@v5

        # Choose python version
        with:
          python-version: "3.12"


      # Step 3:
      # Install project dependencies
      # from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

          # Ruff = Python linter
          # helps catch code mistakes
          pip install ruff


      # Step 4:
      # Run linting checks
      # Example:
      # bad formatting
      # unused imports
      # syntax issues
      - name: Run Python lint checks
        run: |
          ruff check .


      # Step 5:
      # Validate docker-compose.yml
      #
      # This catches:
      # indentation issues
      # broken syntax
      # invalid compose config
      - name: Validate Docker Compose
        run: |
          docker compose config


      # Step 6:
      # Check Python syntax
      #
      # compileall checks if python files
      # can compile successfully
      #
      # Example:
      # missing brackets
      # syntax errors
      # bad imports
      - name: Validate Python files
        run: |
          python -m compileall \
            consumer \
            data-generator \
            kafka-debezium \
            docker/dags